#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000
HISTFILE=~/.config/zsh/.zsh_history
export PATH="$HOME/.mybin/bin":$PATH
export PATH="$HOME/.cargo/bin":$PATH
export PATH="$HOME/go/bin":$PATH
export PATH="$HOME/.local/bin/nvim/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
# export PATH="/usr/local/opt/php@7.4/bin:$PATH"
# export PATH="/usr/local/opt/php@7.4/sbin:$PATH"
export ATUIN_NOBIND="true"
## Installed from pip(x)
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.local/bin/flutter/bin"
export PATH="$PATH:$HOME/.config/composer/vendor/bin"
export PATH="$PATH:$HOME/.local/bin/bun/bin" 
## the following is to get nvm to work
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
export PATH="/home/allen/.config/herd-lite/bin:$PATH"
export PHP_INI_SCAN_DIR="/home/allen/.config/herd-lite/bin:$PHP_INI_SCAN_DIR"
export FZF_DEFAULT_OPTS='--color=fg:#ebfafa,bg:#282a36,hl:#37f499 --color=fg+:#ebfafa,bg+:#212337,hl+:#37f499 --color=info:#f7c67f,prompt:#04d1f9,pointer:#7081d0 --color=marker:#7081d0,spinner:#f7c67f,header:#323449'
