#!/bin/sh

## autoload vcs and colors
autoload -Uz vcs_info
autoload -U colors && colors

# enable only git 
zstyle ':vcs_info:*' enable git 

# setup a hook that runs before every ptompt. 
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst

# add a function to check for untracked files in the directory.
# from https://github.com/zsh-users/zsh/blob/master/Misc/vcs_info-examples
zstyle ':vcs_info:git*+set-message:*' hooks git-untracked
# 
+vi-git-untracked(){
    if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]] && \
        git status --porcelain | grep '??' &> /dev/null ; then
        # This will show the marker if there are any untracked files in repo.
        # If instead you want to show the marker only if there are untracked
        # files in $PWD, use:
        # [[ -n $(git ls-files --others --exclude-standard) ]] ; then
        hook_com[staged]+='+' # signify new files with a bang
    fi
}

zstyle ':vcs_info:*' check-for-changes true
# zstyle ':vcs_info:git:*' formats " %r/%S %b %m%u%c "
# Generic Dark # zstyle ':vcs_info:git:*' formats " %F{39}(%F{202}%m%u%c%F{220} %F{205}%b%F{39})"
zstyle ':vcs_info:git:*' formats " %F{109}(%F{208}%m%u%c%F{214} %F{208}%b%F{109})"

# format our main prompt for hostname current folder, and permissions.
# Genric Dark # PROMPT="%B%F{39}[%F{159}allen%F{202}@%F{159}work%F{39}] %(?:%F{190}➜ :%F{202}➜ )%F{230}%1~%{$reset_color%}"
# PROMPT="%B%F{109}[%F{229}allen%F{167}@%F{229}work%F{109}] %(?:%F{142}➜ :%F{167}➜ )%F{167}%1~%{$reset_color%}"
# PROMPT="%B%F{017}[%F{088}allen%F{017}|%F{088}home%F{017}] %(?:%F{017}➜ :%F{088}➜ )%F{088}%1~%{$reset_color%}"
PROMPT="%B%F{blue}[%F{white}%n%F{red}@%F{white}%m%F{blue}] %(?:%F{green}➜ :%F{red}➜ )%F{cyan}%c%{$reset_color%}"
# PROMPT="%F{green}%n@%m %~ %{$reset_color%}%#> "
PROMPT+="\$vcs_info_msg_0_ "
RPROMPT="%*"
# TODO look into this for more colors
# https://stevelosh.com/blog/2010/02/my-extravagant-zsh-prompt/
# also ascii escape codes
